# Generated by Django 4.2.28 on 2026-02-24 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_sessions', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('peak_concurrent', models.IntegerField(default=0)),
                ('avg_duration', models.DurationField(blank=True, null=True)),
                ('mobile_sessions', models.IntegerField(default=0)),
                ('desktop_sessions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Session Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_type', models.CharField(default='unknown', max_length=20)),
                ('browser', models.CharField(default='unknown', max_length=50)),
                ('os', models.CharField(default='unknown', max_length=50)),
                ('location_city', models.CharField(blank=True, max_length=100, null=True)),
                ('location_country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remember_me', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='user_sessio_user_id_ecb8d3_idx'), models.Index(fields=['session_key'], name='user_sessio_session_8ec2cc_idx'), models.Index(fields=['last_activity'], name='user_sessio_last_ac_ec3541_idx')],
            },
        ),
    ]
