# Generated by Django 4.2.28 on 2026-02-19 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('failed_login', 'Failed Login Attempt'), ('account_locked', 'Account Locked'), ('permission_denied', 'Permission Denied'), ('suspicious_activity', 'Suspicious Activity'), ('role_changed', 'Role Assignment Changed'), ('password_changed', 'Password Changed'), ('session_hijack', 'Potential Session Hijacking'), ('multiple_logins', 'Multiple Concurrent Logins')], max_length=30)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='low', max_length=10)),
                ('description', models.TextField()),
                ('username_attempted', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', '-timestamp'], name='audit_secur_event_t_96dcb7_idx'), models.Index(fields=['risk_level', '-timestamp'], name='audit_secur_risk_le_0dbfc1_idx'), models.Index(fields=['resolved', '-timestamp'], name='audit_secur_resolve_c126c5_idx'), models.Index(fields=['ip_address', '-timestamp'], name='audit_secur_ip_addr_76f717_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('employee_id_accessed', models.CharField(blank=True, max_length=20)),
                ('employee_name_accessed', models.CharField(blank=True, max_length=200)),
                ('access_type', models.CharField(choices=[('list_view', 'Employee List View'), ('detail_view', 'Employee Detail View'), ('profile_view', 'Profile View'), ('search', 'Employee Search'), ('export', 'Data Export'), ('edit', 'Employee Edit'), ('create', 'Employee Create'), ('delete', 'Employee Delete')], max_length=20)),
                ('search_query', models.CharField(blank=True, help_text='Search terms used', max_length=500)),
                ('filters_applied', models.JSONField(blank=True, default=dict, help_text='Filters applied to the view')),
                ('records_accessed', models.PositiveIntegerField(default=1, help_text='Number of records accessed')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(blank=True, help_text='How long the page was viewed', null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='audit_emplo_user_id_040430_idx'), models.Index(fields=['employee', '-timestamp'], name='audit_emplo_employe_8a035f_idx'), models.Index(fields=['access_type', '-timestamp'], name='audit_emplo_access__6d618f_idx'), models.Index(fields=['ip_address', '-timestamp'], name='audit_emplo_ip_addr_d23495_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Stored in case user is deleted', max_length=150)),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('access_denied', 'Access Denied'), ('export', 'Export'), ('import', 'Import'), ('search', 'Search'), ('filter', 'Filter')], max_length=20)),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, help_text='String representation of the object', max_length=200)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='What changed (for updates)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('module', models.CharField(help_text='Which module/app this relates to', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='audit_audit_user_id_ea8c9f_idx'), models.Index(fields=['action', '-timestamp'], name='audit_audit_action_e33994_idx'), models.Index(fields=['module', '-timestamp'], name='audit_audit_module_4e85d9_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx'), models.Index(fields=['ip_address', '-timestamp'], name='audit_audit_ip_addr_ed092b_idx')],
            },
        ),
    ]
