# Generated by Django 4.2.28 on 2026-02-25 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='asset',
            new_name='maintenance_status_2b9a97_idx',
            old_name='maintenance_asset_status_idx',
        ),
        migrations.RenameIndex(
            model_name='asset',
            new_name='maintenance_critica_64effd_idx',
            old_name='maintenance_asset_criticality_idx',
        ),
        migrations.RenameIndex(
            model_name='asset',
            new_name='maintenance_categor_f72001_idx',
            old_name='maintenance_asset_category_idx',
        ),
        migrations.RenameIndex(
            model_name='maintenancelog',
            new_name='maintenance_asset_i_897498_idx',
            old_name='maintenance_log_asset_idx',
        ),
        migrations.RenameIndex(
            model_name='maintenanceschedule',
            new_name='maintenance_next_du_32c0b6_idx',
            old_name='maintenance_schedule_next_due_idx',
        ),
        migrations.RenameIndex(
            model_name='maintenanceschedule',
            new_name='maintenance_is_acti_6d8baa_idx',
            old_name='maintenance_schedule_active_idx',
        ),
        migrations.RenameIndex(
            model_name='workorder',
            new_name='maintenance_status_c6a240_idx',
            old_name='maintenance_wo_status_idx',
        ),
        migrations.RenameIndex(
            model_name='workorder',
            new_name='maintenance_priorit_0e12ec_idx',
            old_name='maintenance_wo_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='workorder',
            new_name='maintenance_asset_i_762468_idx',
            old_name='maintenance_wo_asset_status_idx',
        ),
        migrations.RenameIndex(
            model_name='workorder',
            new_name='maintenance_assigne_1b74ff_idx',
            old_name='maintenance_wo_assigned_idx',
        ),
    ]
