# Generated by Django 4.2.28 on 2026-02-27 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import maintenance.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0002_rename_maintenance_asset_status_idx_maintenance_status_2b9a97_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalDatasheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('datasheet', 'Technical Datasheet'), ('manual', 'User Manual'), ('schematic', 'Schematic / Drawing'), ('certificate', 'Certificate'), ('warranty', 'Warranty Document'), ('other', 'Other')], default='datasheet', max_length=20)),
                ('file', models.FileField(upload_to=maintenance.models.datasheet_upload_path)),
                ('version', models.CharField(blank=True, help_text='e.g. v1.0, Rev A', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasheets', to='maintenance.asset')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Technical Datasheet',
                'verbose_name_plural': 'Technical Datasheets',
                'ordering': ['-created_at'],
            },
        ),
    ]
