# Generated by Django 4.2.28 on 2026-02-27 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0003_technicaldatasheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicaldatasheet',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_datasheets', to=settings.AUTH_USER_MODEL),
        ),
    ]
